config/routes.rb
Rails.application.routes.draw do
mount SolidusPaypalBraintree::Engine, at: '/solidus_paypal_braintree'
  
  filter :locale
  get 'banner/upload'
  post 'banner/upload', as: :upload
  root 'home#index'
  get 'home', to: 'home#index', as: 'home'
  get 'welcome', to: 'landing#index', as: 'landing'
  mount Spree::Core::Engine, at: '/'
# DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banner_controller.rb
class BannerController < ApplicationController
  def upload
    if current_spree_user&.has_spree_role?("admin") then
      if request.method.upcase == 'POST'
        @uploader =  BannerUploader.new
        @uploader.store!(params[:banner][:image])
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < Spree::HomeController
  def index
    @welcome = cookies[:welcome]
    if @welcome != 'yes'
      redirect_to landing_path
      return
    end
    @home = true
    @best_sellers = Spree::Product.select("spree_products.*, SUM(spree_line_items.quantity) as total_qty, spree_line_items.variant_id").
    joins(:line_items).joins("INNER JOIN spree_orders ON spree_orders.id = spree_line_items.order_id").
    where("spree_orders.state = 'complete'").
    group("spree_line_items.variant_id, spree_products.id").order("total_qty DESC")
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @welcome = cookies[:welcome]
    if @welcome == 'yes'
      redirect_to home_path
    else
      cookies[:welcome] = {value: 'yes', expires: 10.minutes}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banner_helper.rb
module BannerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/banner/upload.html.erb
<div class='grid-y grid-frame align-center'>
    <div class='grid-x align-center'>
        <%= @file %>
        <%= form_tag upload_path , class:'ui form', multipart: true  do %>
            <div class="inline field">
                <label>Choose image to upload</label>
                <%= file_field :banner, :image, accept: 'image/*' %>
            </div>
            <div class='field'>
                <%= submit_tag "Upload", class: 'ui button'%>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div id="banner" class="show-for-medium grid-y align-center grid-frame">
    <div class="cell grid-x align-center align-self-middle">
      <h1 id="medium" class="type-it raleway"></h1>
    </div>
</div>
<div id="small-banner" class="show-for-small-only grid-y align-center grid-frame">
      <div class="cell grid-x align-center align-self-middle">
        <h1 id="small" class="type-it mon"></h1>
      </div>
</div>
<div id='about-us' class='about-us show-for-medium grid-container grid-x align-center'>
  <div class='cell medium-8'>
    <p class='text-center raleway'>
      Manifested from culture formed on the streets – from the confidence of hip hop to the grit of punk, YONKERS is the epitome of high-end streetwear. Not taking things too seriously, enjoying the ride, giving zero fucks about what other people think, whilst maintaining a level of integrity, is the irreverent and independent minded individual we hope to reach out to.
    </p>
    <p class='text-center raleway'>
    Derived from the word Jonkheer, a term of nobility, which literally translates to young lord or young lady. Also a suburb in the bronx of New York city, YONKERS is a direct reflection of its name, creating a juxtaposition between ideas of youth and playfulness alongside sophistication, culture and forward thinking.
    </p>
  </div>
</div>

<div id='about-us' data-interchange="[https://yonkers.com.au/wp-content/uploads/2018/11/new-img.jpg, small]" class=' about-us show-for-small-only grid-container grid-x align-center'>
  <div class='cell medium-8 small-10'>
    <p class='text-center raleway'>
      Manifested from culture formed on the streets – from the confidence of hip hop to the grit of punk, YONKERS is the epitome of high-end streetwear. Not taking things too seriously, enjoying the ride, giving zero fucks about what other people think, whilst maintaining a level of integrity, is the irreverent and independent minded individual we hope to reach out to.
    </p>
    <p class='text-center raleway'>
    Derived from the word Jonkheer, a term of nobility, which literally translates to young lord or young lady. Also a suburb in the bronx of New York city, YONKERS is a direct reflection of its name, creating a juxtaposition between ideas of youth and playfulness alongside sophistication, culture and forward thinking.
    </p>
  </div>
</div>

<div class='grid-container grid-x'>
  <h2 id='best-seller-header' class="raleway cell shrink">"BEST-SELLER"</h2>
</div>

<%= render partial: 'spree/shared/products', locals: { products: @best_sellers, taxon: @taxon } unless @best_sellers.empty? %>
<% if @best_sellers.empty? %>
<div class='grid-y align-center grid-frame'>
  <h4 class='raleway text-center no-product-found'  id='no-product-found'><%= t('spree.no_products_found') %></h4>
</div>
<% end %>

app/views/landing/index.html.erb
<div id='landing' class='grid-y grid-frame align-center'>
    <div class='grid-x align-center'>
        <div class='cell medium-3 small-7 animated pulse infinite'>
            <%= link_to home_path, data:{turbolinks: false} do %>
                <%= image_tag 'yonker-logo.png', id:'logo' %>
            <% end %>
        </div>
    </div>
</div>

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>
<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <div class="field field-required" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname, t('spree.first_name') %>
    <%= form.text_field :firstname, class: 'required', autocomplete: address_type + ' given-name', required: true, autofocus: true %>
  </div>

  <div class="field" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname, t('spree.last_name') %>
    <%= form.text_field :lastname, autocomplete: address_type + ' family-name' %>
  </div>

  <% if Spree::Config[:company] %>
    <div class="field" id=<%="#{address_id}company" %>>
      <%= form.label :company, t('spree.company') %>
      <%= form.text_field :company, autocomplete: address_type + ' organization' %>
    </div>
  <% end %>

  <div class="field field-required" id=<%="#{address_id}address1" %>>
    <%= form.label :address1, t('spree.street_address') %>
    <%= form.text_field :address1, class: 'required', autocomplete: address_type + ' address-line1',  required: true %>
  </div>

  <div class="field" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, I18n.t('spree.street_address_2') %>
    <%= form.text_field :address2, autocomplete: address_type + ' address-line2' %>
  </div>

  <div class="field field-required" id=<%="#{address_id}city" %>>
    <%= form.label :city, t('spree.city') %>
    <%= form.text_field :city, class: 'required', autocomplete: address_type + ' address-level2',  required: true %>
  </div>

  <div class="field field-required" id=<%="#{address_id}country" %>>
    <%= form.label :country_id, t('spree.country') %>
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {},
          class: 'required',
          autocomplete: address_type + ' country-name',
          required: true
        %>
    </span>
  </div>

  <% if Spree::Config[:address_requires_state] %>
    <div class="field field-required" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state, t('spree.state') %>

      <span class="js-address-fields" style="display: none;">
        <%=
          form.collection_select(
            :state_id, address.country.states, :id, :name,
            {include_blank: true},
            {
              class: have_states ? 'required' : '',
              style: have_states ? '' : 'display: none;',
              disabled: !have_states,
              autocomplete: address_type + ' address-level1',
            })
          %>
        <%=
          form.text_field(
            :state_name,
            class: !have_states ? 'required' : '',
            style: have_states ? 'display: none;' : '',
            disabled: have_states,
            autocomplete: address_type + ' address-level1',
          )
        %>
      </span>
      <noscript>
        <%= form.text_field :state_name, class: 'required', autocomplete: address_type + ' address-level1',  required: true %>
      </noscript>
    </div>
  <% end %>

  <div class="field <%= 'field-required' if address.require_zipcode? %>" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode, t('spree.zip') %>
    <%= form.text_field :zipcode, class: "#{'required' if address.require_zipcode?}", autocomplete: address_type + ' postal-code',  required: true %>
  </div>

  <div class="field <%= 'field-required' if address.require_phone? %>" id=<%="#{address_id}phone" %>>
    <%= form.label :phone, t('spree.phone') %>
    <% phone_hash = address.require_phone? ? { class: 'required', required: true } : {} %>
    <%= form.phone_field :phone, phone_hash.merge({ autocomplete: address_type + ' home tel' }) %>
  </div>

  <% if Spree::Config[:alternative_shipping_phone] %>
    <div class="field" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, t('spree.alternative_phone') %>
      <%= form.phone_field :alternative_phone, autocomplete: address_type + ' tel'%>
    </div>
  <% end %>
</div>

app/views/spree/address/_form_hidden.html.erb
<%= form.hidden_field :firstname %>
<%= form.hidden_field :lastname %>
<%= form.hidden_field :company %>
<%= form.hidden_field :address1 %>
<%= form.hidden_field :address2 %>
<%= form.hidden_field :city %>
<%= form.hidden_field :country_id %>
<%= form.hidden_field :state_id %>
<%= form.hidden_field :state_name %>
<%= form.hidden_field :zipcode %>
<%= form.hidden_field :phone %>
<%= form.hidden_field :alternative_phone %>

app/views/spree/checkout/_address.html.erb
<div class="columns alpha six" data-hook="billing_fieldset_wrapper">
  <fieldset id="billing" data-hook>
    <%= form.fields_for :bill_address do |bill_form| %>
      <legend align="center"><%= t('spree.billing_address') %></legend>
      <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
    <% end %>
  </fieldset>
</div>

<div class="columns omega six" data-hook="shipping_fieldset_wrapper">
  <fieldset id="shipping" data-hook>
    <%= form.fields_for :ship_address do |ship_form| %>
      <legend align="center"><%= t('spree.shipping_address') %></legend>
      <div class="checkbox" data-hook="use_billing">
        <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
        <%= label_tag :order_use_billing, t('spree.use_billing_address'), id: 'use_billing' %>
      </div>
      <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
    <% end %>
  </fieldset>
</div>
<hr class="clear" />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t('spree.save_and_continue'), class: 'continue button primary' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address">
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, t('spree.save_my_address') %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<fieldset id="order_details" data-hook>
  <div class="clear"></div>
  <legend align="center"><%= t('spree.confirm') %></legend>
  <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <% Spree::Frontend::Config[:require_terms_and_conditions_acceptance].tap do |requires_acceptance| %>
    <% if requires_acceptance %>
      <div class="terms_and_conditions" data-hook="terms_and_conditions">
        <div class="policy"><%= render partial: "spree/checkout/terms_and_conditions" %></div>
        <%= check_box_tag :accept_terms_and_conditions, 'accepted', false %>
        <%= label_tag :accept_terms_and_conditions, t('spree.agree_to_terms_of_service') %>
      </div>
    <% end %>

    <%= submit_tag t('spree.place_order'),
      disabled: requires_acceptance,
      class: "continue button primary #{ 'disabled' if requires_acceptance }" %>
  <% end %>

  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_coupon_code.html.erb
<div class="coupon-code" data-hook='coupon_code'>
  <%= form_for order, url: update_checkout_path(order.state) do |form| %>
    <%= form.label :coupon_code %>
    <%= form.text_field :coupon_code, placeholder: :coupon_code %>

    <button type="submit" class="button coupon-code-apply-button" id="coupon-code-apply-button">
      <%= t('spree.apply_code') %>
    </button>
  <% end %>

  <div id='coupon_status'></div>
</div>

app/views/spree/checkout/_delivery.html.erb
<fieldset id='shipping_method' data-hook>
  <legend align="center"><%= t('spree.delivery') %></legend>
  <div class="inner" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>

        <div class="shipment">
          <h3 class="stock-location" data-hook="stock-location">
            <%= t('spree.package_from') %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h3>

          <table class="stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= t('spree.item') %></th>
              <th><%= t('spree.qty') %></th>
              <th><%= t('spree.price') %></th>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image">
                    <%= render 'spree/shared/image', image: item.variant.display_image, size: :mini %>
                  </td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h5 class="stock-shipping-method-title"><%= t('spree.shipping_method') %></h5>
          <ul class="radios shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= t('spree.unshippable_items') %>
          </h3>
          <table class="stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= t('spree.item') %></th>
              <th><%= t('spree.qty') %></th>
              <th><%= t('spree.price') %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image">
                    <%= render 'spree/shared/image', image: variant.display_image, size: :mini %>
                  </td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <%= form.label :special_instructions, t('spree.shipping_instructions') %><br />
        <%= form.text_area :special_instructions, cols: 40, rows: 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t('spree.save_and_continue'), class: 'continue button primary' %>
</div>

app/views/spree/checkout/_payment.html.erb
<fieldset id="payment" data-hook>
  <legend align="center"><%= t('spree.payment_information') %></legend>
  <div data-hook="checkout_payment_step">
    <% if @wallet_payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">
          <%= t('spree.use_existing_cc') %>
        </label>
        <br/>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">
          <%= t('spree.use_new_cc_or_payment_method') %>
        </label>
      </div>

      <div id="existing_cards">
        <div class="field" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @wallet_payment_sources.each do |wallet_payment_source| %>
                <%=
                  render(
                    partial: "spree/checkout/existing_payment/#{wallet_payment_source.payment_source.payment_method.partial_name}",
                    locals: {
                      wallet_payment_source: wallet_payment_source,
                      default: wallet_payment_source == @default_wallet_payment_source,
                    }
                  )
                %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>

    <div id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
      <p>
        <label>
          <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
          <%= t(method.name, scope: 'spree.payment_methods', default: method.name) %>
        </label>
      </p>
      <% end %>
    </div>

    <ul id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.partial_name}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>
    <br style="clear:both;" />
  </div>
</fieldset>

<br class="space" />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t('spree.save_and_continue'), class: 'continue button primary' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_summary.html.erb
<h3><%= t('spree.order_summary') %></h3>

<table data-hook="order_summary">
  <tbody>
    <tr data-hook="item_total">
      <td><strong><%= t('spree.item_total') %>:</strong></td>
      <td><strong><%= order.display_item_total.to_html %></strong></td>
    </tr>

    <% if order.line_item_adjustments.nonzero.exists? %>
      <tbody data-hook="order_details_promotion_adjustments">
        <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tbody data-hook="order_details_tax_adjustments">
      <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %></td>
          <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
        </tr>
      <% end %>
    </tbody>

    <% if order.passed_checkout_step?("delivery") && order.shipments.any? %>
      <tr data-hook="shipping_total">
        <td><%= t('spree.shipping_total') %>:</td>
        <td><%= Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency).to_html %></td>
      </tr>

      <% if order.shipment_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_shipment_promotion_adjustments">
          <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %>:</td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    <% end %>

    <% if order.adjustments.nonzero.eligible.exists? %>
      <tbody id="summary-order-charges" data-hook>
        <% order.adjustments.nonzero.eligible.each do |adjustment| %>
        <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
          <tr class="total">
            <td><%= adjustment.label %>:</td>
            <td><%= adjustment.display_amount.to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <% if order.total_applicable_store_credit > 0.0 %>
      <tr data-hook="checkout-summary-store-credit">
        <td><%= t('spree.store_credit.store_credit') %>:</td>
        <td><%= order.display_total_applicable_store_credit.to_html %></td>
      </tr>
    <% end %>

    <tr data-hook="order_total">
      <td><strong><%= t('spree.order_total') %>:</strong></td>
      <td><strong><span id='summary-order-total'><%= order.display_order_total_after_store_credit.to_html %></span></strong></td>
    </tr>
  </tbody>
</table>

<% if order.state == 'payment' %>
  <%= render 'coupon_code', order: order %>
<% end %>

app/views/spree/checkout/_terms_and_conditions.en.html.erb
Put your terms and conditions here

app/views/spree/checkout/edit.html.erb
<div id="checkout" data-hook>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>

  <div class="row" data-hook="checkout_header">
    <h1 class="columns three alpha" data-hook="checkout_title"><%= t('spree.checkout') %></h1>
    <div class="columns thirteen omega" data-hook="checkout_progress"><%= checkout_progress %></div>
  </div>

  <div class="row" data-hook="checkout_content">
    <div class="columns <%= if @order.state != 'confirm' then 'alpha twelve' else 'alpha omega sixteen' end %>" data-hook="checkout_form_wrapper">
      <%= form_for @order, url: update_checkout_path(@order.state), html: { id: "checkout_form_#{@order.state}" } do |form| %>
        <% if @order.state == 'address' || !@order.email? %>
          <div class="field field-required" style='clear: both'>
            <%= form.label :email %><br />
            <%= form.email_field :email, required: true %>
          </div>
        <% end %>
        <%= render @order.state, form: form %>
      <% end %>
    </div>
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="columns omega four">
        <%= render partial: 'summary', locals: { order: @order } %>
      </div>
    <% end %>
  </div>
</div>

<script>
Spree.current_order_id = "<%= @order.number %>"
Spree.current_order_token = "<%= @order.guest_token %>"
</script>

app/views/spree/checkout/existing_payment/_gateway.html.erb
<tr id="<%= dom_id(wallet_payment_source, 'spree')%>" class="<%= cycle('even', 'odd') %>">
  <td><%= wallet_payment_source.payment_source.name %></td>
  <td><%= wallet_payment_source.payment_source.display_number %></td>
  <td><%= wallet_payment_source.payment_source.month %></td>
  <td><%= wallet_payment_source.payment_source.year %></td>
  <td>
    <%= radio_button_tag "order[wallet_payment_source_id]", wallet_payment_source.id, default, class: "existing-cc-radio" %>
  </td>
</tr>

app/views/spree/checkout/payment/_gateway.html.erb
<%= image_tag 'credit_cards/credit_card.gif', id: 'credit-card-image' %>
<% param_prefix = "payment_source[#{payment_method.id}]" %>

<div class="field field-required">
  <%= label_tag "name_on_card_#{payment_method.id}", t('spree.name_on_card') %>
  <%= text_field_tag "#{param_prefix}[name]", "#{@order.billing_firstname} #{@order.billing_lastname}", { id: "name_on_card_#{payment_method.id}", autocomplete: "cc-name" } %>
</div>

<div class="field field-required" data-hook="card_number">
  <%= label_tag "card_number", t('spree.card_number') %>
  <%= text_field_tag "#{param_prefix}[number]", '', {id: 'card_number', class: 'required cardNumber', size: 19, maxlength: 19, autocomplete: "cc-number", type: "tel" } %>
  <span id="card_type" style="display:none;">
    ( <span id="looks_like" ><%= t('spree.card_type_is') %> <span id="type"></span></span>
      <span id="unrecognized"><%= t('spree.unrecognized_card_type') %></span>
    )
  </span>
</div>

<div class="field field-required" data-hook="card_expiration">
  <%= label_tag "card_expiry", t('spree.expiration') %>
  <%= text_field_tag "#{param_prefix}[expiry]", '', id: 'card_expiry', class: "required cardExpiry", placeholder: "MM / YY", type: "tel" %>
</div>

<div class="field field-required" data-hook="card_code">
  <%= label_tag "card_code", t('spree.card_code') %>
  <%= text_field_tag "#{param_prefix}[verification_value]", '', {id: 'card_code', class: 'required cardCode', size: 5, type: "tel", autocomplete: "off" } %>
  <%= link_to "(#{t('spree.what_is_this')})", spree.cvv_path, target: '_blank', "data-hook" => "cvv_link", id: "cvv_link" %>
</div>

<% if @order.bill_address %>
  <%= fields_for "#{param_prefix}[address_attributes]", @order.bill_address do |f| %>
    <%= render partial: 'spree/address/form_hidden', locals: { form: f } %>
  <% end %>
<% end %>

<%= hidden_field_tag "#{param_prefix}[cc_type]", '', id: "cc_type", class: 'ccType' %>

app/views/spree/home/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render partial: 'spree/shared/taxonomies' %>
  </div>
<% end %>

<div data-hook="homepage_products">
  <% cache(cache_key_for_products) do %>
    <%= render partial: 'spree/shared/products', locals: { products: @products } %>
  <% end %>
</div>

app/views/spree/layouts/spree_application.html.erb
<html lang="<%= I18n.locale %>">
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
  </head>
  <body>
    <%= render partial: 'spree/shared/header' %>
    <% if flash.any? %>
    <div class='ui basic modal'>
        <div class="ui icon header">
          <div>
            <%= image_tag 'main-logo.png' %>
          </div>
          Notification
        </div>
        <div class="content">
          <% flash.each do |type,message| %>
            <p class='text-center raleway'> <%= message %></p>
          <% end %>
        </div>
        <div class='actions'>
          <div class="ui green basic cancel inverted button">
            <i class="papel plan outline icon"></i>
            Got It!
          </div>
        </div>
      </div>
      <%= javascript_include_tag 'modal_open'%>
    <% end %>
    <%= yield %>
    <%= render partial: 'spree/shared/footer'%>
  </body>
</html>

app/views/spree/products/_image.html.erb
<% if defined?(image) && image %>
  <%= render 'spree/shared/image', image: image, size: :large, itemprop: "image" %>
<% else %>
  <%= render 'spree/shared/image', image: @product.display_image, size: :large, itemprop: "image" %>
<% end %>